[package]

name = "crc"
version = "0.2.0"
authors = ["mrhooray <ruihu.pvt@gmail.com>"]
description = "rust implementation of crc(32, 64)"
keywords = ["crc", "crc32", "crc64", "hash", "checksum"]
readme = "README.md"
repository= "https://github.com/mrhooray/crc-rs.git"
license = "MIT"

[dependencies]
lazy_static = "0.1.*"
